#!/usr/bin/env python3
"""
chatgpt_to_claude.py
====================
Converts a ChatGPT export ZIP into a fully preserved local archive:

  1. One Markdown file per conversation (full history + inline assets)
  2. Binary assets extracted from ZIP or downloaded via OpenAI Files API
  3. Unrecoverable DALL·E images recreated via Claude's vision/image context
  4. Unrecoverable ChatGPT-generated files recreated by Claude from context
  5. Claude-generated summary for every conversation
  6. Master INDEX.md linking all conversations with summaries + asset stats
  7. Optional upload of conversations to Claude API (with deduplication)

Recreation policy
-----------------
  • User-uploaded files  → extracted from ZIP if present; otherwise noted as
                           permanently unrecoverable (OpenAI blocks API download
                           of purpose=user_data files by design).
  • DALL·E images        → extracted from ZIP by size-match first; if missing,
                           recreated via Claude using the original DALL·E prompt
                           and any seed/gen-id metadata preserved in the JSON.
  • Code-interpreter /   → text content preserved inline; binary outputs
    ChatGPT file outputs   recreated by Claude from conversation context.

Recreated artifacts are clearly marked in the Markdown with a banner.

Usage:
    pip3 install anthropic openai
    python3 chatgpt_to_claude.py path/to/export.zip

Environment variables (optional – script will prompt if absent):
    ANTHROPIC_API_KEY
    OPENAI_API_KEY
"""

from __future__ import annotations

import base64
import getpass
import json
import os
import re
import sys
import tempfile
import time
import zipfile
from datetime import datetime
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

# ── Constants ─────────────────────────────────────────────────────────────────

MANIFEST_FILE    = "manifest.json"
ANTHROPIC_MODEL  = "claude-sonnet-4-20250514"
OUTPUT_DIR       = Path(tempfile.gettempdir()) / "chatgpt-to-claude"
ASSETS_SUBDIR    = "assets"
API_CALL_DELAY   = 0.6   # seconds between Claude API calls

RECREATED_BANNER = (
    "\n> ⚠️ **RECREATED ARTIFACT** — The original file was not recoverable from "
    "the ChatGPT export. The content below was regenerated by Claude using the "
    "conversation context and any available metadata (e.g. DALL·E prompt/seed). "
    "It may differ from the original.\n"
)

# ── Filename / path helpers ───────────────────────────────────────────────────

def safe_filename(title: str, max_len: int = 60) -> str:
    slug = re.sub(r"[^\w\s-]", "", title).strip()
    slug = re.sub(r"\s+", "_", slug)
    return slug[:max_len] or "untitled"


def ext_for_mime(mime: str) -> str:
    table = {
        "image/webp": ".webp", "image/png": ".png", "image/jpeg": ".jpg",
        "image/gif": ".gif",   "application/pdf": ".pdf",
        "text/plain": ".txt",  "text/csv": ".csv",
        "text/html": ".html",  "application/json": ".json",
        "application/zip": ".zip",
    }
    return table.get(mime, ".bin")


# ── Manifest ──────────────────────────────────────────────────────────────────

def load_manifest(out_dir: Path) -> dict:
    p = out_dir / MANIFEST_FILE
    return json.loads(p.read_text()) if p.exists() else {}


def save_manifest(out_dir: Path, manifest: dict) -> None:
    (out_dir / MANIFEST_FILE).write_text(json.dumps(manifest, indent=2))


# ── ZIP helpers ───────────────────────────────────────────────────────────────

def build_zip_index(zf: zipfile.ZipFile) -> dict[str, str]:
    """Map base-filename → member-path for all non-JSON/HTML members."""
    return {
        Path(m).name: m
        for m in zf.namelist()
        if not m.endswith(("/", ".json", ".html"))
    }


def zip_member_by_size(zf: zipfile.ZipFile, size: int, idx: dict) -> str | None:
    """
    The only reliable link between image_asset_pointer entries and ZIP files
    is the uncompressed byte count stored in the JSON.
    """
    for name, path in idx.items():
        if zf.getinfo(path).file_size == size:
            return path
    return None


# ── Network helpers ───────────────────────────────────────────────────────────

def download_url(url: str, dest: Path) -> bool:
    try:
        req = Request(url, headers={"User-Agent": "chatgpt-to-claude/2.0"})
        with urlopen(req, timeout=20) as r:
            dest.write_bytes(r.read())
        return True
    except (URLError, HTTPError):
        return False


def download_openai_file(file_id: str, dest: Path, oa) -> bool:
    """
    Try the OpenAI Files API.  Works for purpose=assistants / assistants_output.
    Silently fails for purpose=user_data (OpenAI blocks those by policy).
    """
    if oa is None or not file_id:
        return False
    try:
        data = oa.files.content(file_id)
        dest.write_bytes(data.read())
        return True
    except Exception:
        return False


def file_id_from_pointer(pointer: str) -> str | None:
    m = re.search(r"(file-[A-Za-z0-9]+)", pointer or "")
    return m.group(1) if m else None


# ── Message parsing ───────────────────────────────────────────────────────────

def parse_messages(conv: dict) -> list[dict]:
    """
    Walk the mapping tree depth-first and return a flat list of messages.
    Each message dict:
        role, author_name, text, binary_parts, ts
    binary_parts list items:
        kind (image|audio|video|file), asset_pointer, size_bytes,
        width, height, dalle_meta, filename, mime_type
    """
    mapping    = conv.get("mapping", {})
    child_map: dict[str, list[str]] = {}
    root_id    = None

    for nid, node in mapping.items():
        parent = node.get("parent")
        if parent is None or parent not in mapping:
            root_id = nid
        else:
            child_map.setdefault(parent, []).append(nid)

    messages: list[dict] = []

    def dfs(nid: str) -> None:
        node = mapping.get(nid)
        if not node:
            return
        raw = node.get("message")
        if raw:
            role   = raw.get("author", {}).get("role", "unknown")
            aname  = raw.get("author", {}).get("name", "")
            if role in ("user", "assistant", "tool", "system"):
                content      = raw.get("content", {})
                ctype        = content.get("content_type", "text")
                parts        = content.get("parts", [])
                text_parts:   list[str]  = []
                binary_parts: list[dict] = []

                for part in parts:
                    if isinstance(part, str):
                        text_parts.append(part)
                    elif isinstance(part, dict):
                        _parse_part(part, text_parts, binary_parts)

                # tether_quote / browsing text blocks
                if ctype == "tether_browsing_display":
                    text_parts.append(f"[Web result: {content.get('result','')}]")

                text = "\n".join(text_parts).strip()
                if text or binary_parts:
                    messages.append({
                        "role":         role,
                        "author_name":  aname,
                        "text":         text,
                        "binary_parts": binary_parts,
                        "ts":           raw.get("create_time"),
                    })
        for child in child_map.get(nid, []):
            dfs(child)

    if root_id:
        dfs(root_id)
    return messages


def _parse_part(part: dict, text_parts: list, binary_parts: list) -> None:
    ctype = part.get("content_type", "")

    if ctype == "image_asset_pointer":
        meta  = part.get("metadata", {}) or {}
        binary_parts.append({
            "kind":          "image",
            "asset_pointer": part.get("asset_pointer", ""),
            "size_bytes":    part.get("size_bytes"),
            "width":         part.get("width"),
            "height":        part.get("height"),
            "dalle_meta":    meta.get("dalle"),
            "filename":      None,
            "mime_type":     "image/webp",
        })

    elif ctype in ("audio_asset_pointer", "video_asset_pointer"):
        binary_parts.append({
            "kind":          ctype.replace("_asset_pointer", ""),
            "asset_pointer": part.get("asset_pointer", ""),
            "size_bytes":    part.get("size_bytes"),
            "width":         None, "height": None,
            "dalle_meta":    None,
            "filename":      None,
            "mime_type":     None,
        })

    elif ctype == "multimodal_text":
        for sub in part.get("parts", []):
            if isinstance(sub, str):
                text_parts.append(sub)
            elif isinstance(sub, dict):
                _parse_part(sub, text_parts, binary_parts)

    elif ctype == "text":
        t = part.get("text", "").strip()
        if t:
            text_parts.append(t)

    # tether_quote → inline cite
    elif ctype == "tether_quote":
        url   = part.get("url", "")
        title = part.get("title", "")
        text_parts.append(f"> [{title}]({url})")


# ── Asset recovery ────────────────────────────────────────────────────────────

def recover_assets(
    messages:   list[dict],
    assets_dir: Path,
    zf:         zipfile.ZipFile,
    zip_idx:    dict,
    oa,                          # openai client or None
) -> dict:
    """
    For every binary_part in messages try to recover the file.
    Mutates each binary_part in-place, adding:
        local_fname, local_rel, status
    Returns summary counts.
    """
    assets_dir.mkdir(parents=True, exist_ok=True)
    counts = {"total": 0, "from_zip": 0, "from_api": 0, "from_url": 0, "missing": 0}

    seen_sizes: set[int] = set()  # avoid duplicate ZIP extractions

    for msg in messages:
        for bp in msg.get("binary_parts", []):
            counts["total"] += 1
            pointer  = bp.get("asset_pointer", "")
            size     = bp.get("size_bytes")
            file_id  = file_id_from_pointer(pointer)
            kind     = bp.get("kind", "file")
            mime     = bp.get("mime_type") or ("image/webp" if kind == "image" else "application/octet-stream")
            ext      = ext_for_mime(mime)
            base     = file_id or f"asset_{counts['total']}"
            fname    = f"{base}{ext}"
            dest     = assets_dir / fname
            status   = "missing"

            # 1 — match by size in ZIP (most reliable for DALL·E WebPs)
            if size and size not in seen_sizes and not dest.exists():
                member = zip_member_by_size(zf, size, zip_idx)
                if member:
                    orig_ext = Path(member).suffix or ext
                    dest     = assets_dir / f"{base}{orig_ext}"
                    fname    = dest.name
                    dest.write_bytes(zf.read(member))
                    seen_sizes.add(size)
                    status = "from_zip"
                    counts["from_zip"] += 1

            # 2 — OpenAI Files API (works for assistants_output; fails for user_data)
            if status == "missing" and not dest.exists():
                if download_openai_file(file_id, dest, oa):
                    status = "from_api"
                    counts["from_api"] += 1

            # 3 — signed URL embedded in pointer
            if status == "missing" and pointer.startswith("https://"):
                if download_url(pointer, dest):
                    status = "from_url"
                    counts["from_url"] += 1

            if status == "missing":
                counts["missing"] += 1

            bp["local_fname"] = fname if status != "missing" else None
            bp["local_rel"]   = f"{ASSETS_SUBDIR}/{fname}" if status != "missing" else None
            bp["status"]      = status

    return counts


# ── Claude recreation ─────────────────────────────────────────────────────────

def recreate_assets(
    messages:   list[dict],
    assets_dir: Path,
    ac,          # anthropic client
    conv_title:  str,
) -> int:
    """
    For every still-missing binary_part, ask Claude to recreate it.
    Returns count of successful recreations.
    """
    recreated = 0
    # Build a running transcript so Claude has context for each recreation
    transcript_so_far: list[str] = []

    for msg in messages:
        role_label = msg["role"].upper()
        if msg.get("text"):
            transcript_so_far.append(f"{role_label}: {msg['text']}")

        for bp in msg.get("binary_parts", []):
            if bp.get("status") != "missing":
                continue

            kind       = bp.get("kind", "file")
            dalle_meta = bp.get("dalle_meta") or {}
            size       = bp.get("size_bytes")
            w, h       = bp.get("width"), bp.get("height")
            file_id    = file_id_from_pointer(bp.get("asset_pointer", ""))
            assets_dir.mkdir(parents=True, exist_ok=True)

            try:
                if kind == "image":
                    result = _recreate_image(
                        dalle_meta, w, h, transcript_so_far, ac, assets_dir, file_id
                    )
                else:
                    result = _recreate_file(
                        kind, bp, transcript_so_far, ac, assets_dir, file_id, conv_title
                    )

                if result:
                    bp["local_fname"]  = result["fname"]
                    bp["local_rel"]    = f"{ASSETS_SUBDIR}/{result['fname']}"
                    bp["status"]       = "recreated"
                    bp["recreated_note"] = result.get("note", "")
                    recreated += 1
                    time.sleep(API_CALL_DELAY)

            except Exception as e:
                bp["recreate_error"] = str(e)

    return recreated


def _recreate_image(
    dalle_meta: dict,
    w: int | None,
    h: int | None,
    transcript: list[str],
    ac,
    assets_dir: Path,
    file_id: str | None,
) -> dict | None:
    """
    Use Claude to generate a text description of what the image likely looked like,
    then use the OpenAI DALL·E 3 prompt (stored in the export JSON) plus that
    description to write a recreated-image markdown block.
    Since Claude itself cannot generate images via the messages API, we write
    a detailed recreation-prompt file instead, and note it clearly.
    """
    prompt_text = dalle_meta.get("prompt", "")
    seed        = dalle_meta.get("seed", "")
    gen_id      = dalle_meta.get("gen_id", "")

    if not prompt_text and not transcript:
        return None

    context = "\n".join(transcript[-20:])   # last 20 turns for context

    system = (
        "You are helping reconstruct a lost DALL·E image from a ChatGPT conversation. "
        "Given the original DALL·E prompt and conversation context, write a vivid, detailed "
        "description of what the image most likely depicted. Be specific about composition, "
        "style, colours, subjects, and mood. Also restate the exact DALL·E prompt so the user "
        "can regenerate it themselves."
    )
    user_msg = (
        f"DALL·E prompt: {prompt_text or '(not recorded)'}\n"
        f"Seed: {seed or 'unknown'}  Gen ID: {gen_id or 'unknown'}\n"
        f"Dimensions: {w}×{h}px\n\n"
        f"Conversation context (last turns):\n{context}\n\n"
        "Please write:\n"
        "1. A heading '## Image Description'\n"
        "2. A detailed visual description of what this image likely showed\n"
        "3. A heading '## Regeneration Prompt'\n"
        "4. The exact prompt to paste into DALL·E / Midjourney / Stable Diffusion to recreate it"
    )

    resp    = ac.messages.create(
        model=ANTHROPIC_MODEL, max_tokens=600,
        system=system,
        messages=[{"role": "user", "content": user_msg}],
    )
    content = resp.content[0].text.strip()

    # Save as a markdown recreation file
    fname = f"{file_id or 'dalle_recreation'}_RECREATED.md"
    (assets_dir / fname).write_text(
        f"# DALL·E Image Recreation\n\n"
        f"_Original DALL·E prompt: {prompt_text}_  \n"
        f"_Seed: {seed}  Gen ID: {gen_id}_  \n"
        f"_Original dimensions: {w}×{h}px_\n\n"
        + RECREATED_BANNER + "\n\n" + content,
        encoding="utf-8",
    )
    return {
        "fname": fname,
        "note":  f"DALL·E image recreated as description + regeneration prompt. Original prompt: {prompt_text[:100]}",
    }


def _recreate_file(
    kind:       str,
    bp:         dict,
    transcript: list[str],
    ac,
    assets_dir: Path,
    file_id:    str | None,
    conv_title: str,
) -> dict | None:
    """
    Use Claude to recreate a non-image file (code, CSV, document, etc.)
    based on conversation context.
    """
    context = "\n".join(transcript[-30:])

    system = (
        "You are helping reconstruct a file that was generated by ChatGPT but is no longer "
        "available for download. Reproduce the file content as faithfully as possible based "
        "on the conversation context. Output ONLY the raw file content — no explanation, "
        "no markdown fences unless the file itself is markdown."
    )
    user_msg = (
        f"Conversation title: '{conv_title}'\n"
        f"Missing file type: {kind}\n"
        f"File ID hint: {file_id or 'unknown'}\n\n"
        f"Conversation context:\n{context}\n\n"
        "Please reproduce the file content that ChatGPT generated."
    )

    resp    = ac.messages.create(
        model=ANTHROPIC_MODEL, max_tokens=2000,
        system=system,
        messages=[{"role": "user", "content": user_msg}],
    )
    content = resp.content[0].text.strip()

    # Pick a reasonable extension
    ext   = ".txt"
    lower = context.lower()
    if any(k in lower for k in ("csv", "spreadsheet", "comma-separated")):
        ext = ".csv"
    elif any(k in lower for k in ("python", ".py", "def ", "import ")):
        ext = ".py"
    elif any(k in lower for k in ("javascript", ".js", "const ", "function ")):
        ext = ".js"
    elif any(k in lower for k in ("html", "<div", "<body")):
        ext = ".html"
    elif any(k in lower for k in ("markdown", "## ", "**")):
        ext = ".md"

    fname = f"{file_id or 'file_recreation'}_RECREATED{ext}"
    header = (
        f"# Recreated File\n\n"
        f"_Originally generated by ChatGPT in conversation: '{conv_title}'_\n"
        + RECREATED_BANNER + "\n\n"
    )
    (assets_dir / fname).write_text(header + content, encoding="utf-8")
    return {
        "fname": fname,
        "note":  f"ChatGPT-generated {kind} file recreated by Claude from conversation context.",
    }


# ── Markdown rendering ────────────────────────────────────────────────────────

def render_markdown(conv: dict, messages: list[dict]) -> str:
    title    = conv.get("title", "Untitled Conversation")
    created  = conv.get("create_time")
    date_str = (
        datetime.utcfromtimestamp(created).strftime("%Y-%m-%d %H:%M UTC")
        if created else "Unknown date"
    )

    lines = [
        f"# {title}",
        "",
        f"**Exported from ChatGPT** · {date_str}",
        "",
        "---",
        "",
    ]

    for msg in messages:
        role  = msg["role"]
        aname = msg.get("author_name", "")
        if role == "system":
            continue

        if role == "tool" and "dalle" in aname:
            label = "🎨 **DALL·E**"
        else:
            label = {
                "user":      "🧑 **You**",
                "assistant": "🤖 **ChatGPT**",
            }.get(role, f"_{role}_")

        ts_str = ""
        if msg.get("ts"):
            ts_str = "  \n*" + datetime.utcfromtimestamp(msg["ts"]).strftime("%H:%M UTC") + "*"

        lines += [f"{label}{ts_str}", ""]

        if msg.get("text"):
            lines += [msg["text"], ""]

        for bp in msg.get("binary_parts", []):
            lines += _render_binary_part(bp)

        lines += ["---", ""]

    return "\n".join(lines)


def _render_binary_part(bp: dict) -> list[str]:
    kind       = bp.get("kind", "file")
    status     = bp.get("status", "missing")
    fname      = bp.get("local_fname")
    rel        = bp.get("local_rel")
    dalle_meta = bp.get("dalle_meta") or {}
    lines: list[str] = []

    # DALL·E metadata header
    if dalle_meta:
        prompt = dalle_meta.get("prompt", "")
        seed   = dalle_meta.get("seed", "")
        gen_id = dalle_meta.get("gen_id", "")
        lines.append("> **DALL·E generated image**")
        if prompt:
            lines.append(f"> Prompt: *{prompt[:300]}{'…' if len(prompt)>300 else ''}*")
        if seed:
            lines.append(f"> Seed: `{seed}` · Gen ID: `{gen_id}`")
        lines.append("")

    if status in ("from_zip", "from_api", "from_url"):
        source_badge = {"from_zip": "📦 from ZIP", "from_api": "☁️ via API", "from_url": "🌐 via URL"}[status]
        if kind == "image":
            lines += [f"![image]({rel})", f"*({source_badge})*", ""]
        else:
            lines += [f"[📎 {fname}]({rel})  *({source_badge})*", ""]

    elif status == "recreated":
        note = bp.get("recreated_note", "")
        lines += [
            RECREATED_BANNER,
            f"[📄 {fname}]({rel})",
            f"*{note}*" if note else "",
            "",
        ]

    else:  # missing / unrecoverable
        pointer = bp.get("asset_pointer", "")
        file_id = file_id_from_pointer(pointer)
        w, h    = bp.get("width"), bp.get("height")
        size    = bp.get("size_bytes")
        dim     = f"{w}×{h}px · " if w and h else ""
        sz      = f"{size:,} bytes · " if size else ""
        err     = bp.get("recreate_error", "")
        lines += [
            f"> ❌ **{kind.capitalize()} unrecoverable** ({dim}{sz}id: `{file_id or 'unknown'}`)",
        ]
        if "user_data" in pointer or not pointer.startswith("https"):
            lines.append(
                "> This was a user-uploaded file. OpenAI permanently blocks API "
                "retrieval of user uploads (purpose=user_data) and does not include "
                "them in the export ZIP."
            )
        if err:
            lines.append(f"> Recreation attempt failed: `{err}`")
        lines.append("")

    return lines


# ── Claude summary ────────────────────────────────────────────────────────────

def summarise(messages: list[dict], ac, title: str) -> str:
    parts, total = [], 0
    for m in messages:
        if m["role"] == "system":
            continue
        line = f"{m['role'].upper()}: {m['text']}"
        if total + len(line) > 6000:
            parts.append("… [truncated]")
            break
        parts.append(line)
        total += len(line)

    resp = ac.messages.create(
        model=ANTHROPIC_MODEL, max_tokens=400,
        messages=[{"role": "user", "content": (
            f'Summarise this ChatGPT conversation titled "{title}" in 3–6 sentences '
            f"(second person, e.g. 'You asked…'). Cover: main topic, key outputs, "
            f"any unresolved questions or next steps.\n\nTranscript:\n" + "\n\n".join(parts)
        )}],
    )
    return resp.content[0].text.strip()


# ── Claude upload ─────────────────────────────────────────────────────────────

def upload_to_claude(messages: list[dict], ac, title: str, summary: str) -> str:
    transcript = "\n\n".join(
        f"{m['role'].upper()}: {m['text']}"
        for m in messages if m["role"] != "system" and m.get("text")
    )
    resp = ac.messages.create(
        model=ANTHROPIC_MODEL, max_tokens=200,
        system=(
            f'Imported ChatGPT conversation: "{title}"\n\nSummary:\n{summary}\n\n'
            "Full transcript below. Continue the conversation or answer questions about it."
        ),
        messages=[{"role": "user", "content": (
            f"Imported conversation:\n\n{transcript}\n\n"
            "Please confirm receipt and readiness to continue."
        )}],
    )
    return resp.id


# ── Index ─────────────────────────────────────────────────────────────────────

def write_index(out_dir: Path, entries: list[dict]) -> None:
    lines = [
        "# ChatGPT Export — Conversation Index",
        "",
        f"_Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}_  ",
        f"_Total conversations: {len(entries)}_",
        "",
        "---",
        "",
    ]
    for e in entries:
        lines += [f"## [{e['title']}]({e['rel_md_path']})", ""]
        lines += [e.get("summary") or "*(No summary)*", ""]

        ac  = e.get("asset_count", 0)
        sv  = e.get("asset_saved", 0)
        rc  = e.get("asset_recreated", 0)
        fl  = e.get("asset_failed", 0)
        if ac:
            parts = [f"{sv} recovered"]
            if rc:
                parts.append(f"{rc} recreated by Claude")
            if fl:
                parts.append(f"{fl} unrecoverable")
            lines += [f"📎 **Assets ({ac} total):** " + " · ".join(parts), ""]

        if e.get("uploaded"):
            lines += [f"☁️ _Uploaded to Claude · ref: `{e.get('upload_ref','')}`_", ""]

        lines += [f"_Processed: {e.get('processed_at','')}_", "", "---", ""]

    (out_dir / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")


# ── CLI helpers ───────────────────────────────────────────────────────────────

def ask(q: str) -> bool:
    while True:
        a = input(f"{q} [y/n]: ").strip().lower()
        if a in ("y", "yes"):
            return True
        if a in ("n", "no"):
            return False
        print("  Please type y or n.")


def hr(ch: str = "─", n: int = 62) -> None:
    print(ch * n)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    print()
    hr("═")
    print("  ChatGPT → Claude Converter  v2.0")
    hr("═")
    print()

    if len(sys.argv) < 2:
        print("Usage: python3 chatgpt_to_claude.py path/to/export.zip")
        sys.exit(1)

    zip_path = Path(sys.argv[1]).expanduser().resolve()
    if not zip_path.exists():
        print(f"❌  Not found: {zip_path}")
        sys.exit(1)

    # ── Anthropic key ─────────────────────────────────────────────────────────
    ac_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not ac_key:
        ac_key = getpass.getpass("🔑  Anthropic API key: ").strip()
    if not ac_key:
        print("❌  Anthropic API key required.")
        sys.exit(1)

    try:
        import anthropic as _anthropic
        ac = _anthropic.Anthropic(api_key=ac_key)
    except ImportError:
        print("❌  Run: pip3 install anthropic")
        sys.exit(1)

    # ── OpenAI key (optional) ─────────────────────────────────────────────────
    print()
    print("  An OpenAI API key enables recovery of DALL·E images via the Files API.")
    print("  User-uploaded files cannot be recovered regardless (OpenAI policy).")
    oa_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not oa_key:
        oa_key = getpass.getpass("🔑  OpenAI API key (Enter to skip): ").strip()

    oa = None
    if oa_key:
        try:
            import openai as _openai
            oa = _openai.OpenAI(api_key=oa_key)
            print("  ✅  OpenAI client ready.")
        except ImportError:
            print("  ⚠️   pip3 install openai  — continuing without OpenAI downloads.")
    else:
        print("  ⏭️   Skipping OpenAI file downloads.")

    # ── Output dir ────────────────────────────────────────────────────────────
    out_dir = OUTPUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    print()
    print(f"📁  Output: {out_dir}")
    print()

    manifest = load_manifest(out_dir)
    print(f"📋  Manifest: {len(manifest)} previously processed conversation(s).")
    print()

    # ── Open ZIP ──────────────────────────────────────────────────────────────
    print(f"📦  Opening {zip_path.name} …")
    with zipfile.ZipFile(zip_path) as zf:
        conv_file = next((n for n in zf.namelist() if n.endswith("conversations.json")), None)
        if not conv_file:
            print("❌  conversations.json not found in ZIP.")
            sys.exit(1)

        conversations = json.loads(zf.read(conv_file))
        zip_idx       = build_zip_index(zf)
        print(f"✅  {len(conversations)} conversation(s), {len(zip_idx)} binary asset(s) in ZIP.")
        print()

        # ── Phase 1 ───────────────────────────────────────────────────────────
        hr()
        print("  Phase 1: Parse · Extract assets · Recreate missing · Summarise")
        hr()
        print()

        index_entries: list[dict] = []
        new_convs:     list[tuple] = []

        for i, conv in enumerate(conversations, 1):
            conv_id = conv.get("id", f"conv_{i}")
            title   = conv.get("title", "Untitled")
            slug    = f"{i:04d}_{safe_filename(title)}"
            print(f"[{i}/{len(conversations)}] {title}")

            if conv_id in manifest:
                print("    ⏭️   Already processed.\n")
                index_entries.append(manifest[conv_id])
                continue

            messages = parse_messages(conv)
            if not messages:
                print("    ⚠️   No messages — skipping.\n")
                continue

            conv_dir   = out_dir / slug
            assets_dir = conv_dir / ASSETS_SUBDIR
            conv_dir.mkdir(parents=True, exist_ok=True)

            # Extract / download assets
            counts = recover_assets(messages, assets_dir, zf, zip_idx, oa)
            if counts["total"]:
                print(
                    f"    📎  Assets: {counts['from_zip']} from ZIP · "
                    f"{counts['from_api']} via API · {counts['from_url']} via URL · "
                    f"{counts['missing']} missing"
                )

            # Recreate missing assets with Claude
            n_recreated = 0
            if counts["missing"]:
                print(f"    🤖  Asking Claude to recreate {counts['missing']} missing asset(s) …")
                n_recreated = recreate_assets(messages, assets_dir, ac, title)
                print(f"    ✅  {n_recreated} asset(s) recreated.")

            # Render markdown
            md_text = render_markdown(conv, messages)
            md_path = conv_dir / f"{slug}.md"
            md_path.write_text(md_text, encoding="utf-8")
            rel_md  = str(md_path.relative_to(out_dir))
            print(f"    ✍️   Markdown → {rel_md}")

            # Summary
            try:
                summary = summarise(messages, ac, title)
                time.sleep(API_CALL_DELAY)
                print("    📝  Summary generated.")
            except Exception as e:
                summary = f"⚠️  Summary failed: {e}"
                print(f"    ⚠️   Summary error: {e}")

            n_saved  = counts["from_zip"] + counts["from_api"] + counts["from_url"]
            n_failed = counts["missing"] - n_recreated

            entry = {
                "id":               conv_id,
                "title":            title,
                "rel_md_path":      rel_md,
                "summary":          summary,
                "processed_at":     datetime.utcnow().isoformat(),
                "asset_count":      counts["total"],
                "asset_saved":      n_saved,
                "asset_recreated":  n_recreated,
                "asset_failed":     n_failed,
                "uploaded":         False,
                "upload_ref":       None,
            }
            manifest[conv_id] = entry
            index_entries.append(entry)
            new_convs.append((conv_id, messages, entry))
            save_manifest(out_dir, manifest)
            print()

    # ── Write index ───────────────────────────────────────────────────────────
    write_index(out_dir, index_entries)
    print(f"📄  INDEX.md written.")
    print()

    # ── Phase 2: upload ───────────────────────────────────────────────────────
    pending = [(cid, msgs, e) for cid, msgs, e in new_convs if not manifest[cid]["uploaded"]]

    if not pending:
        print("✅  Nothing new to upload.")
    else:
        hr()
        print(f"  Phase 2: Upload to Claude API  ({len(pending)} conversation(s))")
        hr()
        print()
        if ask("🚀  Proceed with upload?"):
            for i, (cid, msgs, entry) in enumerate(pending, 1):
                print(f"[{i}/{len(pending)}] {entry['title']}")
                try:
                    ref = upload_to_claude(msgs, ac, entry["title"], entry["summary"])
                    manifest[cid].update({"uploaded": True, "upload_ref": ref,
                                          "uploaded_at": datetime.utcnow().isoformat()})
                    save_manifest(out_dir, manifest)
                    print(f"    ✅  ref: {ref}")
                    time.sleep(API_CALL_DELAY)
                except Exception as e:
                    print(f"    ❌  {e}")
                print()
            write_index(out_dir, list(manifest.values()))
            print("📄  INDEX.md updated with upload status.")
        else:
            print("⏭️   Upload skipped.")

    print()
    hr("═")
    print(f"  🎉  Done!")
    print(f"  📄  Index  : {out_dir}/INDEX.md")
    print(f"  📝  Chats  : {out_dir}/<conversation>/<conversation>.md")
    print(f"  📎  Assets : {out_dir}/<conversation>/{ASSETS_SUBDIR}/")
    print(f"  📋  Log    : {out_dir}/{MANIFEST_FILE}")
    hr("═")
    print()


if __name__ == "__main__":
    main()
